version: '3'

services:
  db:
    image: postgres
    env_file:
      - ./db.env

  # don't call it redis, it will miss up redis image (a bug I noticed)
  redis_db:
    image: redis:6
    volumes: ./redis-data:/redis-data
    ports:
    - 6379:6379
    command: redis-server

  web:
    build: .
    ports:
      - 8000:8000
    links:
      - db
      - redis_db
    command: python manage.py migrate & python manage.py runserver