# Generated by Django 3.1 on 2020-08-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.FloatField(max_length=10)),
                ('image_path', models.URLField()),
                ('store', models.CharField(blank=True, choices=[('BG', 'Badr Group'), ('EL', 'Egypt Laptop'), ('HE', 'High End'), ('MX', 'Maximum'), ('SPC', 'Sigma PC')], max_length=20, null=True)),
                ('seller_image', models.ImageField(blank=True, default=None, null=True, upload_to='')),
            ],
        ),
    ]
