# Generated by Django 3.1 on 2020-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.URLField(default='http://placehold.it/500x500'),
        ),
    ]
